### ISSUE TITLE
Error deserializing a flattened struct

### ISSUE THREAD

**Issue by djnalluri** [tafia/quick-xml#777] opened 2024-07-01 20:09 UTC
There's an issue deserializing flattened structs. The below reproducer works fine for the JSON test but fails for the XML one. It panics with `invalid type: map, expected a string`.

Reproducer:
```rust
use serde::Deserialize;

#[derive(Deserialize)]
pub struct RecordWrapper {
    pub key: String,

    #[serde(flatten)]
    pub data: RecordData
}

#[derive(Deserialize)]
pub struct RecordData {
    foo: String,
    bar: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_xml() {
        let xml = r"
            <Record>
                <key>Record Key</key>
                <foo>A</foo>
                <bar>B</bar>
            </Record>";

        let record = quick_xml::de::from_str(xml).unwrap();
        verify_record(record);
    }

    #[test]
    fn parse_json() {
        let record = serde_json::from_str(r#"{
            "key": "Record Key",
            "foo": "A",
            "bar": "B"
        }"#).unwrap();
        verify_record(record);
    }

    fn verify_record(record: RecordWrapper) {
        assert_eq!(record.key, "Record Key");
        let data = record.data;
        assert_eq!(data.foo, "A");
        assert_eq!(data.bar, "B");
    }
}
```

**Comment by Mingun** [comment] 2024-07-01 20:25
Yes, unfortunately this is unavoidable flaw of the flatten design. Duplicate of Duplicate of #714

**Closed by Mingun** 2024-07-01 20:25 UTC
Labels: bug, duplicate, serde
