### ISSUE TITLE
Design for namespaces

### ISSUE THREAD

**Issue by mohe2015** [tafia/quick-xml#316] opened 2021-08-30 10:29 UTC
Also the namespace thing is probably not a final fix. Although I don't know XML really well I think we would need some mapping from namespace urls. Let me give an example (CalDAV):
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:propfind xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:d="DAV:" xmlns:nc="http://nextcloud.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:s="http://sabredav.org/ns">
  <d:prop xmlns:x1="http://apple.com/ns/ical/" xmlns:x2="http://nextcloud.com/ns">
    <d:current-user-principal />
  </d:prop>
</d:propfind>
```
should as far as I understand it should be equivalent to:
```xml
<?xml version="1.0" encoding="utf-8"?>
<dav:propfind xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:dav="DAV:" xmlns:nc="http://nextcloud.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:s="http://sabredav.org/ns">
  <dav:prop xmlns:x1="http://apple.com/ns/ical/" xmlns:x2="http://nextcloud.com/ns">
    <dav:current-user-principal />
  </dav:prop>
</dav:propfind>
```
The way yaserde implements this is you specify a mapping of namespace-shorthands to namespace urls:
```rust
#[yaserde(
    namespace = "d: DAV:",
    namespace = "s: http://sabredav.org/ns",
    namespace = "cal: urn:ietf:params:xml:ns:caldav",
    namespace = "cs: http://calendarserver.org/ns/",
    namespace = "oc: http://owncloud.org/ns",
    namespace = "nc: http://nextcloud.org/ns"
)]
```
and then can use these shorthands. A potentially easier but maybe also annoying way would be to directly use the url maybe like:
```rust
#[serde(rename = "$unflatten=urn:ietf:params:xml:ns:caldav href")]
```
where we should choose delimiters as invalid characters of the namespace url. But then you would need to store all `xmlns:` attributes on a stack or so to know which shorthand this belongs to.

_Originally posted by @mohe2015 in https://github.com/tafia/quick-xml/issues/306#issuecomment-898941176_

**Comment by Mingun** [comment] 2022-05-25 16:02
I have a clearer vision how namespaces should be supported in the Deserializer. I'm working on that, so I close this as duplicate of #218

**Closed by Mingun** 2022-05-25 16:02 UTC
Labels: enhancement, serde, namespaces
