### ISSUE TITLE
Serde deserialization: Namespaces can lead to erroneous "duplicate field" errors

### ISSUE THREAD

**Issue by roblabla** [tafia/quick-xml#547] opened 2023-01-27 16:00 UTC
There appears to be a bug when trying to deserialize XML mixing named and unnamed namespaces (e.g. `xmlns=a` and `xmlns:a=a`). Here's a quick repro, which I think shows the problem better than I can explain it:

```rust
#[test]
fn repro() {
    #[derive(Deserialize)]
    struct Root {
        lol: Vec<Lol>
    }

    #[derive(Deserialize)]
    struct Lol {}

    let x: Root = quick_xml::de::from_str(r#"<root>
        <lol xmlns="http://whatever.com/schema/whatever" />
        <ohai:lol xmlns:ohai="http://whatever.com/schema/whatever" />
    </root>"#).unwrap();
}
```

Output:

```
---- test::repro stdout ----
thread 'test::repro' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("duplicate field `lol`")', src/lib.rs:163:179
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I would expect both `lol` and `ohai:lol` to get appended to the `lol: Vec<Lol>` of the `Root` struct.

**Comment by Mingun** [comment] 2023-01-27 21:16
Thanks for report, this is duplicate of #218

**Closed by Mingun** 2023-01-27 21:16 UTC
Labels: serde, namespaces
