### ISSUE TITLE
Cant deserialize elements where field name has a namespace - Causes Serde round-trip fail

### ISSUE THREAD

**Issue by rrichardson** [tafia/quick-xml#493] opened 2022-10-08 01:35 UTC
When deserializing fields which have been renamed to include a namespaced name, e.g. `xsi:type`  whether this is done with or without the `@` to specify an attribute,  the result is 
```
"missing field `@xsi:type`"
```

I have a struct : 

```rust 
pub struct Grantee {
    ...
    #[serde(rename = "@xsi:type")]
    pub r#type: TypeEnum,
    #[serde(rename="@xmlns:xsi")]
    pub ns_import: Option<String>
}
``` 
which serializes correctly.  The generated XML for Grantee is correct, I have verified it in an xml validator according to an xsd.  However, when deserializing, it can't find `@xsi:type`  also, if I remove the `@` prefix, and render it as a child, the result is the same.  

This seems to be true for any name which has been renamed to include a `:` 

Frankly, I'd just like to ignore namespaces entirely.  It would be great if I could just treat `xsi:type` as an opaque string that matches my renamed field.

**Comment by rrichardson** [comment] 2022-10-08 01:36
here is an example of the rendered XML that should match the above struct: 

```rust 
<Grantee xsi:type="Group" xmlns:xsi="http://s3.amazonaws.com/doc/2006-03-01/">
    <EmailAddress>1kwHgTGiMgGDE</EmailAddress>
    <URI>9oTEbGypCwgT7</URI>
</Grantee>
```

**Comment by Mingun** [comment] 2022-10-08 06:43
Duplicate of #347

**Closed by Mingun** 2022-10-08 06:43 UTC
Labels: bug, duplicate, serde, namespaces
