### ISSUE TITLE
Add a function to parse inner elements literally

### ISSUE THREAD

**Issue by althonos** [tafia/quick-xml#161] opened 2019-05-23 23:41 UTC
Hi ! 

I'm trying to implement an [RDF/XML parser](https://github.com/pchampin/sophia_rs/pull/9) using `quick_xml`, and I'm currently missing the possibility to parse [literal XML constructs](https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-XML-literals). Basically, this only means either changing `Reader.read_to_end` to return the total bytes read until reaching the end, or adding a new `read_literal` method that would do that.

I can work on a PR if you don't have time to do this by the way :smiley:

**Comment by tafia** [comment] 2019-08-14 06:11
> I can work on a PR if you don't have time to do this by the way smiley

I'd love it! Thanks and sorry for the super long delay

**Comment by Mingun** [comment] 2022-05-21 22:18
Duplicate of #257

**Closed by Mingun** 2022-05-21 22:18 UTC
