### ISSUE TITLE
Serialisation: support for namespaces and declarations

### ISSUE THREAD

**Issue by romatthe** [tafia/quick-xml#282] opened 2021-04-11 17:41 UTC
First of all, thank you for this great library!

Using the `serde::Serialize` attribute/API, is there a way to support `xmlns` attributes on a struct (without having to manually implement and rename them as fields)? If not, do you think it would be possible to create custom derive macros for this, or would that be to complicated?

I currently have to do something along these lines:

```rust
#[derive(Serialize)]
pub struct User {
    #[serde(rename = "xmlns:a")]
    xmlns1: String,
    #[serde(rename = "xmlns:b")]
    xmlns2: String
}

impl User {
    pub fn new() -> Self {
        Self {
            xmlns1: "http://www.w3.org/user1".to_owned(),
            xmlns2: "http://www.w3.org/user2".to_owned(),
        }
    }
}
```

... which is just very unpleasant to use if you're working with tons of structs.

It would be awesome if something along the lines of this would be possible:

```rust
#[derive(Serialize)]
#[xml(xmlns = "a = http://www.w3.org/user1")]
#[xml(xmlns = "b = http://www.w3.org/user2")]
pub struct User {

}
```

Also, does the library currently support serializing structs with proper XML declarations (i.e. `<?xml version='1.0' encoding='UTF-8' ?>`, etc)?

Thanks!

**Comment by Mingun** [comment] 2022-05-25 16:26
Duplicate of #218

**Closed by Mingun** 2022-05-25 16:26 UTC
Labels: enhancement, serde, namespaces
