### ISSUE TITLE
How to deserialize an unknown type

### ISSUE THREAD

**Issue by ice-curtain** [tafia/quick-xml#585] opened 2023-03-31 08:04 UTC
xml:
```xml
<a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="1_Office 主题​​">
  <a:extLst>
    <a:ext uri="{05A4C25C-085E-4340-85A3-A5531E510DB2}">
      <thm15:themeFamily xmlns:thm15="http://schemas.microsoft.com/office/thememl/2012/main"
                         name="Office Theme"
                         id="{62F939B6-93AF-4DB8-9C6B-D6C7DFDC589F}"
                         vid="{4A3C46E8-61CC-4603-A589-7422A47A8E4A}"/>
    </a:ext>
    <a:ext uri="{05A4C25C-085E-4340-85A3-A5531E510DB2}">
      <thm15:themeFamily xmlns:thm15="http://schemas.microsoft.com/office/thememl/2012/main"
                         name="Office Theme"
                         id="{62F939B6-93AF-4DB8-9C6B-D6C7DFDC589F}"
                         vid="{4A3C46E8-61CC-4603-A589-7422A47A8E4A}"/>
    </a:ext>
  </a:extLst>
</a:theme>
```

struct:
```rust
#[derive(Serialize, Deserialize)]
#[serde(rename(serialize = "a:theme", deserialize = "theme"))]
pub struct Theme {
    #[serde(rename = "xmlns:a")]
    a: Option<String>,

    #[serde(rename = "xmlns:r")]
    r: Option<String>,

    #[serde(rename = "xmlns:p")]
    p: Option<String>,

    #[serde(rename = "xmlns:s")]
    s: Option<String>,

    name: String,

    #[serde(rename(serialize = "a:extLst", deserialize = "extLst"))]
    ext_lst: Option<CtOfficeArtExtensionList>,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct CtOfficeArtExtensionList {
    ext: Vec<HashMap<String,Box<dyn Any>>>,
}
```

ext schema:
```xml
<xsd:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
```
Because the requirement of the schema for `ext` is 'xsd:any', I can't imagine any structure that can support it. The structure `ext: Vec<HashMap<String,Box<dyn Any>>>` is just an example, because I don't know how to organize this structure to achieve the goal.

**Comment by Mingun** [comment] 2023-03-31 15:29
You should define an enum similar to [`serde_value::Value`](https://docs.rs/serde-value/0.7.0/serde_value/enum.Value.html), and manually implement `Deserialize` and `Serialize` traits for it (unlikely that they can be derived and works as required). Remember, that XML format are more tricky that JSON, so you should be a little creative to find a way to handle it. Start with this small set of test cases and think about how you will map it to your `XmlValue` enum:
```xml
<root a="b"/>
<root a="b" c="d"/>

<root><a/></root>
<root><a/><b/></root>
<root><a/><a/></root>

<root>text</root>

<root a="b" c="d"><e/></root>
<root a="b" c="d">text</root>

<root><a b="c"/></root>
<root><a>text</a></root>
```
Hint: try to convert those examples to JSON using online tools to get some ideas

**Comment by Mingun** [comment] 2024-01-03 21:04
We need to have a special type to store XML node, so I close this as duplicate of #257

**Closed by Mingun** 2024-01-03 21:04 UTC
Labels: question, serde

**Comment by enricozb** [comment] 2024-01-04 02:55
Thoughts on this idea? https://github.com/enricozb/quick-xml/commit/7b4b3f851a50ae9dbb45d54edfdc7c2374ec59d0

Specifically, I'm adding a new special field name `$raw` that only deserializes into a string.

It lets you do stuff like this:
```rust
const xml: &str = r#"
  <who-cares>
    <foo property="value">
      test
      <bar><bii/><int>1</int></bar>
      test
      <baz/>
    </foo>
  </who-cares>
"#;

#[derive(Deserialize, Debug)]
struct Root {
  #[serde(rename = "$raw")]
  value: usize,
}

let root = quick_xml::de::from_str::<Root>(&xml).unwrap();

println!("parsed: {root:?}");
```

This prints
```
parsed: Root { value: "<foo property=\"value\">test<bar><bii></bii><int>1</int></bar>test<baz></baz></foo>" }
```

One of the problems with this approach is that it doesn't save _exactly_ what was in the XML file. This would be ideal because we could likely avoid any allocations, like `serde_json::value::RawValue`, and we would preserve formatting, and not trim spaces.

It's possible my initial idea could be fixed up to disable trimming temporarily of the reader during `raw_string` use.

**Comment by enricozb** [comment] 2024-01-04 03:07
Whoops, meant to post this on #257...
