### ISSUE TITLE
serde serialization seems to ignore `Writer` indent

### ISSUE THREAD

**Issue by ratmice** [tafia/quick-xml#240] opened 2020-10-30 06:56 UTC
in the serde serialize [tests](https://github.com/tafia/quick-xml/blob/95c924131749f43f458745b8a6a04f8ab80c0c2d/src/se/mod.rs#L464-L473) the writer is constructed with `Writer::new_with_indent(...)`,
 but the `serialize()` always ends up serializing unindented onto a single unindented line.
The non-serde tests [test_writer_indent](https://github.com/tafia/quick-xml/blob/f93f386b5af42954139e4e9c713e86f612d93a87/tests/unit_tests.rs#L241) looks to work ok however -- so I presume this is an issue with `se/mod.rs`?

**Comment by Mingun** [comment] 2022-05-21 20:57
Duplicate of #361

**Closed by Mingun** 2022-05-21 20:57 UTC
