### ISSUE TITLE
How to Deserialize With Duplicate Attributes

### ISSUE THREAD

**Issue by zicklag** [tafia/quick-xml#318] opened 2021-09-01 20:02 UTC
Hey there, I'm not sure there's a good way around this or not, but I've got an XML [schema](https://ebible.org/usfx/usfx.htm) that has both an attribute on the tag called `id`, and also a child tag named `id`, and there's no way with the deserializer to differentiate between the two. I just get an error:

     Custom("duplicate field `id`")

Maybe we need to be able to do something like `serde(rename = "$attribute=id")` for the attribute, so that it can tell the difference between the attribute and the child tags?

**Comment by Mingun** [comment] 2022-05-25 16:17
Duplicate of #293

**Closed by Mingun** 2022-05-25 16:17 UTC
Labels: enhancement, serde
