### ISSUE TITLE
How to represent any node using this library and Serde

### ISSUE THREAD

**Issue by eirnym** [tafia/quick-xml#805] opened 2024-09-23 23:14 UTC
I'd like to represent any node as is without mapping this value to an object, like I can do with `serde_json::Value`. This is often useful when node could not be mapped strictly or I'd like to load XML, edit part of it and save XML back without actually manipulating data where I don't need to

```rust
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub struct RootNode {
    known: KnownType,
    unknown: Vec<Value>,
}

pub struct KnownType {
   data: Option<()>,
}
```

for `Vec<Value>` I'd prefer just `Value`, but it could be impossible

**Comment by Mingun** [comment] 2024-09-24 05:48
Duplicate of #257

**Closed by Mingun** 2024-09-24 05:48 UTC

**Comment by eirnym** [comment] 2024-09-24 07:50
@Mingun this issue doesn't represent serialization, which is crucial for me as well
