### ISSUE TITLE
enum text content is (incorrectly) indented

### ISSUE THREAD

**Issue by torkleyy** [tafia/quick-xml#729] opened 2024-03-21 14:20 UTC
```rs
#[derive(Clone, Debug, Serialize, PartialEq)]
#[serde(rename = "response")]
pub struct Response {
    #[serde(rename = "intent", with = "quick_xml::serde_helpers::text_content")]
    pub intent: Intent,
}

#[derive(Clone, Debug, Serialize, PartialEq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Intent {
    Accept,
    Reject,
}
```

results in

```xml
<response>
  <intent>
    ACCEPT
  </intent>
</response>
```

when indentation is enabled. In my understanding it's incorrect that the element content (`intent`) contains whitespace.

**Comment by Mingun** [comment] 2024-03-21 17:43
Yes, I think, this is undesired behavior and we need to fix it

**Comment by Mingun** [comment] 2024-09-30 17:15
Duplicate of #655

**Closed by Mingun** 2024-09-30 17:15 UTC
Labels: bug, help wanted, serde
