### ISSUE TITLE
`Unexpected Event::End(...)` or `missing field '...'`

### ISSUE THREAD

**Issue by jimy-byerley** [tafia/quick-xml#567] opened 2023-03-01 11:33 UTC
Hello dear maintainers

I'm trying to alter [`ethercat-esi`](https://github.com/ethercat-rs/ethercat-esi) to use `quick_xml` instead of `serde-xml-rs`. This is pretty straight forward as `ethercat-esi` crate is only using the `serde` macros and calling the xml parser at one place.
```rust 
// ethercat-esi//src/lib.rs
let raw_info: parser::EtherCATInfo = quick_xml::de::from_str(xml)
            .map_err(|e| Error::new(ErrorKind::Other, e.to_string()))?;
```
Running this code (in lib or in a test file of that crate) gives me the following output on both xml files
```rust
$ target/debug/test/some ~/erob-custom.xml
Error: Custom { kind: Other, error: "Unexpected `Event::End(\"Groups\")`" }

// then I comment the Groups section in the xml
$ target/debug/test/some ~/erob-custom.xml
Error: Custom { kind: Other, error: "missing field `ProductCode`" }

// then I change quick-xml version from v0.27.1 to v0.26.0
$ target/debug/test/some ~/erob-custom.xml
Error: Custom { kind: Other, error: "missing field `Sm`" }
```

These fields and the Groups markups are good in the xml files. And it doesn't seems to come from the serde declarations of the xml data (in `ethercat-esi/src/mod.rs`), so I suggest there is an issue with the way the `quick_xml` functions are calling or checking results of the serde deserialization functions. (especially since the error is not the same depending on the version of `quick_xml`)
How do you think I could solve this problem ?

**Comment by jimy-byerley** [comment] 2023-03-01 12:09
I forgot to add the xml files I was using for tests: [xml.zip](https://github.com/tafia/quick-xml/files/10860770/xml.zip)

**Comment by Mingun** [comment] 2023-03-01 14:51
This is duplicate of #510 and the error is generated by this (and the others `Option<Vec<T>>`) piece of code:
https://github.com/ethercat-rs/ethercat-esi/blob/3d295ca4c1f8c86f1046a85ce93d14b5d85dcc04/src/parser/mod.rs#L43-L46

This is already fixed in master and I plan to release soon (I think in week or two). You can also change the definition to `Vec<T>` with the default value as suggested [here](https://github.com/tafia/quick-xml/issues/510#issuecomment-1315558671).

**Comment by jimy-byerley** [comment] 2023-03-02 08:05
Thank you very much for your quick answer
I tried both the solutions you proposed, but I still get the `missing field` issue

Here are the branchs where I put the modifications you suggested
- [quick-xml-fix](https://github.com/jimy-byerley/ethercat-esi/tree/quick-xml-fix)  modifies `ethercat-esi` to use `quick-xml master` branch (commit `40b14489f0cd6ada136f11ae7aceecced1a82f9d`)
- [no-options](https://github.com/jimy-byerley/ethercat-esi/tree/no-options)  modifies `ethercat-esi` to use `quick-xml = 1.27.1` and remove mentions of `Option<Vec>`

Is there something I missed ? :thinking:

**Comment by Mingun** [comment] 2023-03-02 11:02
Yeah, forgot to mention that you should also tweak your mappings, because quick-xml expect that attributes are named starting from `@`. Check out [the reference](https://docs.rs/quick-xml/latest/quick_xml/de/index.html#mapping-xml-to-rust-types).

**Comment by jimy-byerley** [comment] 2023-03-02 15:51
Indeed, I didn't paid pattention to the fact that quick-xml wasn't implicitely using attributes instead of fields when they were missing. Sorry for that.
I [tweaked it](https://github.com/jimy-byerley/ethercat-esi/commit/6057015ec0f1ccc603f53089e98c17a3db338055) as you said. It does find more fields, but now it it gets an even stranger error:  `missing field '@StartAddress'`

**Comment by Mingun** [comment] 2023-03-02 17:47
Probably that attribute is really missed? Check the all `Sm` elements in your XML to see if that true.

**Comment by jimy-byerley** [comment] 2023-03-03 08:02
Unfortunately it is not missing :thinking: 
The same error happens with the unit tests of `ethercat-esi`, those fields are not missing either but what is strange is that only `@StartAddress` is not found whereas before a lot of fields where. I wonder if there is something special about it. I double checked for mistypes but it appears to be fine ...

**Comment by jimy-byerley** [comment] 2023-03-03 08:44
Maybe it will be easier to reproduce the issue using the unit tests rather than using my xml files.
those are the failing unit tests in `ethercat-esi`:

- [parser::tests::device](https://github.com/jimy-byerley/ethercat-esi/blob/6057015ec0f1ccc603f53089e98c17a3db338055/src/parser/mod.rs#L419)
- [parser::tests::ethercat_info_crated_by_igh](https://github.com/jimy-byerley/ethercat-esi/blob/6057015ec0f1ccc603f53089e98c17a3db338055/src/parser/mod.rs#L282)
- [parser::tests::ethercat_info_crated_by_weidmueller](https://github.com/jimy-byerley/ethercat-esi/blob/6057015ec0f1ccc603f53089e98c17a3db338055/src/parser/mod.rs#L266)

**Comment by Mingun** [comment] 2023-03-03 15:40
Ok, there is a bug when you have a list in the enum variant:
```rust
#[test]
fn issue567() {
    #[derive(Debug, Deserialize, PartialEq)]
    struct Device {
        #[serde(rename = "$value")]
        items: Vec<DeviceProperty>,
    }

    #[derive(Debug, Deserialize, PartialEq)]
    enum DeviceProperty {
        Sm(Vec<()>),
    }

    assert_eq!(// currently failed with Unexpected::End
        Device {
            items: vec![
                DeviceProperty::Sm(vec![()]),
            ]
        },
        // Currently failed at unwrap() with UnexpectedEnd(b"Device")
        from_str("<Device><Sm/></Device>").unwrap()
    );
}
```

**Comment by jimy-byerley** [comment] 2023-03-06 10:18
Hum, like for `Option<Vec>` I guess :thinking:

**Comment by Mingun** [comment] 2023-03-16 17:36
The error probably in the line 2723:
https://github.com/tafia/quick-xml/blob/642de0a28721447822867ec966c79437c1dc1436/src/de/mod.rs#L2715-L2725
We should pass the deserializer with another implementation of `deserialize_seq` method here. The implementation should be similar to
https://github.com/tafia/quick-xml/blob/642de0a28721447822867ec966c79437c1dc1436/src/de/map.rs#L708-L715
but with `de: Deserializer` instead of `map: MapAccess`.

**Closed** 2023-10-12 20:07 UTC
Labels: bug, serde, arrays
