### ISSUE TITLE
How to deserialize an element contains empty string?

### ISSUE THREAD

**Issue by jianse** [tafia/quick-xml#795] opened 2024-08-09 03:57 UTC
```rust
#[derive(Debug, Deserialize)]
struct Text {
    #[serde(rename = "$value")]
    text: String,
}

#[test]
fn test_de() -> Result<()> {
    let xml = r#"<Text> </Text>"#;
    let txt: Text = quick_xml::de::from_str(xml)?;
    let txt = dbg!(txt);
    assert_eq!(txt.text, " ");
    Ok(())
}
```

expect an write space, but gives an error.

```
Error: missing field `$value`
```

**Comment by Mingun** [comment] 2024-08-09 04:32
Whitespaces between markup is not significant and currently that cannot be changed. #285 tracks the ability to change that.

Closed as duplicate of #285

**Closed by Mingun** 2024-08-09 04:32 UTC

**Comment by a-n-d-r-e-w-l** [comment] 2025-12-16 18:59
I'm running into this exact issue on v0.38.4 - the changes introduced in #285 help for some other instances in my data (where there is some non-whitespace text with significant leading/trailing whitespace, the whitespace gets preserved as I need it to), but _pure_ whitespace text still gets removed and treated as a missing field.

I've tested a fair few libraries now (`quick-xml`, `serde-xml-rs`, `xmltree` and `roxmltree`) as well as the `xq` [CLI](https://github.com/kislyuk/yq), and the only one that seems to preserve purely-whitespace text is `roxmltree` - which, unfortunately, lacks serde support and hasn't had an update in a fair while.

I understand that XML generally treats whitespace as foldable, but unfortunately I don't control the data source so I can't ensure that whitespace is wrapped in an appropriate way when it is significant. Would it be possible to add an option for this along the lines of `Config.preserve_empty_text` to passthrough fully-whitespace text to the deserializer?

**Comment by a-n-d-r-e-w-l** [comment] 2025-12-17 09:02
> You may [create](https://docs.rs/quick-xml/latest/quick_xml/de/struct.Deserializer.html#method.borrowing) `Deserializer` from preconfigured `NsReader`, where text trimming is disabled. Does that solve your issue?

I probably should have clarified originally: I've tried setting `Config.trim_text` this way, and it has had no effect.

Minimal example:

```rust
use serde::{Serialize, Deserialize};

const DATA: &str = r#"<s> </s>"#;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Span {
    #[serde(rename = "$text")]
    pub inner: String,
}

fn main() {
    let mut r = quick_xml::NsReader::from_str(DATA);
    r.config_mut().trim_text(false);
    let mut de = quick_xml::de::Deserializer::borrowing(r);
    let s: Span = Deserialize::deserialize(&mut de).unwrap();
    dbg!(s);
}
```

This results in an error `missing field '$text'`. If `DATA` is instead `"<s> . </s>"` then it succeeds as expected, and the `trim_text` setting does indeed work to control whether `" . "` or `"."` is produced, but when `DATA` is left as-is the `trim_text` setting doesn't make a difference.
