### ISSUE TITLE
Fails to parse JMDict which has a large !DOCTYPE section

### ISSUE THREAD

**Issue by udoprog** [tafia/quick-xml#595] opened 2023-04-24 01:29 UTC
File can be downloaded [from here](http://ftp.edrdg.org/pub/Nihongo/JMdict.gz) from here: <https://www.edrdg.org/jmdict/j_jmdict.html>.

I'm not entirely sure what's going on, but a large chunk of the DOCTYPE section is processed, but it stops in the middle and events the following error:

> Note that I've added the byte offset:

```
Only Comment (`--`), CDATA (`[CDATA[`) and DOCTYPE (`DOCTYPE`) nodes can start with a '!', but symbol `B` found (at 8466)
```

This is the following element (inside of the `!DOCTYPE` section):

```xml
<!ELEMENT field (#PCDATA)>
        <!-- Information about the field of application of the entry/sense.
        When absent, general application is implied. Entity coding for
        specific fields of application. -->
```

**Comment by Mingun** [comment] 2023-04-24 04:32
Likely duplicate of #590

**Closed by Mingun** 2023-04-24 04:32 UTC
