### ISSUE TITLE
problems with colon separators

### ISSUE THREAD

**Issue by unshakable-horse** [tafia/quick-xml#591] opened 2023-04-12 05:56 UTC
```rust
fn main() {
    let xml = r#"<p:sldLayoutIdLst>
        <p:sldLayoutId id="2147483649" r:id="rId1"/>
        <p:sldLayoutId id="2147483650" r:id="rId2"/>
    </p:sldLayoutIdLst>"#;
    let result:CtSlideLayoutIdList = quick_xml::de::from_str(xml).unwrap();
    println!("{:?}",quick_xml::se::to_string(&result));
}

#[derive(Serialize,Deserialize,Debug)]
#[serde(rename(serialize = "p:sldLayoutIdLst", deserialize = "sldLayoutIdLst"))]
pub struct CtSlideLayoutIdList {
    #[serde(rename(serialize = "p:sldLayoutId", deserialize = "sldLayoutId"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sld_layout_id: Option<Vec<CtSlideLayoutIdListEntry>>,
}



#[derive(Serialize,Deserialize,Debug)]
pub struct CtSlideLayoutIdListEntry{
    #[serde(rename="@id")]
    pub id_attr:Option<String>,

    #[serde(rename="@r:id")]
    pub r_id_attr:Option<String>,
}
```
i got an error "thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("duplicate field `@id`")'"

**Comment by Mingun** [comment] 2023-04-12 07:55
Namespaces does not supported yet with serde. Duplicate of #218.

**Closed by Mingun** 2023-04-12 07:55 UTC
Labels: serde, namespaces
