### ISSUE TITLE
Loosing attributes during serialization

### ISSUE THREAD

**Issue by mlevkov** [tafia/quick-xml#196] opened 2020-02-15 22:10 UTC
Hello,

I have an XML with some elements that have attributes. It deserializes into a struct ok, but when I serialize to output, the attributes are no longer attributes, but rather individual elements. How do I correctly indicate that attributes need to stay as attributes and nothing else? 

For example, I have the following element with attributes:
```xml
<Representation audioSamplingRate="48000" bandwidth="63700" codecs="mp4a.40.2" id="519678732693145249_AO-00-00-00-71">
```

When I read the element into the struct:
```rust
#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Representation{
    #[serde(rename = "audioSamplingRate")]
    a_audio_sampling_rate: Option<String>,
    #[serde(rename = "bandwidth")]
    a_bandwidth: String,
    #[serde(rename = "codecs")]
    a_codecs: String,
    #[serde(rename = "id")]
    a_id: String,
}
```
It looks and feels right. However, during the output, the serialization step, I get the output that looks like this:
```xml
<Representation>
   <audioSamplingRate>48000</audioSamplingRate>
   <bandwidth>63700</bandwidth>
   <codecs>mp4a.40.2</codecs>
   <id>519678732693145249_AO-00-00-00-71</id>
</Representation>
```
What am I not doing right? Or, what am I missing in this process?
I'm reading the element indicated above, as a string. Also, the output is a string as well.

Thank you,
Max

**Comment by tafia** [comment] 2020-03-07 07:20
Hmm you're right. I see no obvious solution right now, apart from serializing it manually.

**Comment by mlevkov** [comment] 2020-03-09 19:55
@tafia If it was to be serialized manually, how would one go about doing so? Could a sample be constructed that demonstrates such?

**Comment by crusty-dave** [comment] 2020-03-25 06:40
I am having the same issue.

The solution would seem to be to fix serialize_field() in following code:

```
impl<'w, W> ser::SerializeStruct for Struct<'w, W>
where
    W: 'w + Write,
{
    type Ok = ();
    type Error = DeError;

    fn serialize_field<T: ?Sized + Serialize>(
        &mut self,
        key: &'static str,
        value: &T,
    ) -> Result<(), DeError> {
        let key = key.as_bytes();
        self.parent
            .writer
            .write_event(Event::Start(BytesStart::borrowed_name(key)))?;
        value.serialize(&mut *self.parent)?;
        self.parent
            .writer
            .write_event(Event::End(BytesEnd::borrowed(key)))?;
        Ok(())
    }

    fn end(self) -> Result<Self::Ok, DeError> {
        self.parent
            .writer
            .write_event(Event::End(BytesEnd::borrowed(self.name.as_bytes())))?;
        Ok(())
    }
}
```

Instead of this chunk of code:

```
        self.parent
            .writer
            .write_event(Event::Start(BytesStart::borrowed_name(key)))?;
        value.serialize(&mut *self.parent)?;
        self.parent
            .writer
            .write_event(Event::End(BytesEnd::borrowed(key)))?;
```

It seems like it needs something like the following from the example, I am just not sure exactly what:

```
            // adds a new my-key="some value" attribute
            elem.push_attribute(("my-key", "some value"));
```

I just don't know enough about the code to be able to fix it.  Has anyone forked the code to fix this?

**Comment by crusty-dave** [comment] 2020-03-25 07:22
This could be a fix, but I am out of my depth with this:

```
impl<'w, W> Struct<'w, W>
where
    W: 'w + Write,
{
    /// Create a new `Struct`
    pub fn new(parent: &'w mut Serializer<W>, name: &'w str) -> Struct<'w, W> {
        let mut stat = Struct { parent, name };
        write!(stat.parent.writer.inner(), "<").map_err(Error::Io)?;
        name.serialize(&mut *stat.parent)?;
        write!(stat.parent.writer.inner(), ">").map_err(Error::Io)?;

        stat
    }
}

impl<'w, W> ser::SerializeStruct for Struct<'w, W>
where
    W: 'w + Write,
{
    type Ok = ();
    type Error = DeError;

    fn serialize_field<T: ?Sized + Serialize>(
        &mut self,
        key: &'static str,
        value: &T,
    ) -> Result<(), DeError> {
        let key = key.as_bytes();
        // Anything which isn't a "primitive" would lead to malformed XML here...
        write!(self.parent.writer.inner(), " ").map_err(Error::Io)?;
        key.serialize(&mut *self.parent)?;
        write!(self.parent.writer.inner(), "=").map_err(Error::Io)?;

        write!(self.parent.writer.inner(), r#"""#).map_err(Error::Io)?;
        value.serialize(&mut *self.parent)?;
        write!(self.parent.writer.inner(), r#"""#).map_err(Error::Io)?;

        Ok(())
    }

    fn end(self) -> Result<Self::Ok, DeError> {
        write!(self.parent.writer.inner(), "</").map_err(Error::Io)?;
        key.serialize(&mut *self.parent)?;
        write!(self.parent.writer.inner(), ">").map_err(Error::Io)?;
        Ok(())
    }
}
```

**Comment by crusty-dave** [comment] 2020-03-25 22:48
The following seems to be working if you keep simple types at the beginning of your struct and put other embedded structs at the end.

```
    fn serialize_struct(
        self,
        name: &'static str,
        _len: usize,
    ) -> Result<Self::SerializeStruct, DeError> {
        write!(self.writer.inner(), r#"<"#).map_err(Error::Io)?;
        name.serialize(&mut *self)?;
        Ok(Struct::new(self, name))
    }


/// An implementation of `SerializeStruct` for serializing to XML.
pub struct Struct<'w, W>
where
    W: 'w + Write,
{
    parent: &'w mut Serializer<W>,
    name: &'w str,
    attrs: u32,
    needs_close: bool,
}

impl<'w, W> Struct<'w, W>
    where
        W: 'w + Write,
{
    /// Create a new `Struct`
    pub fn new(parent: &'w mut Serializer<W>, name: &'w str) -> Struct<'w, W> {
        Struct { parent, name, attrs: 0, needs_close: true }
    }
}

fn is_basic_type(type_name: &str) -> bool {
    match type_name {
        "bool" | "char" => true,
        "u8" | "u16" | "u32" | "u64" | "u128" => true,
        "i8" | "i16" | "i32" | "i64" | "i128" => true,
        "f32" | "f64" => true,
        "[u8]" => true,
        "alloc::string::String" => true,
        _ => false
    }
}

impl<'w, W> ser::SerializeStruct for Struct<'w, W>
    where
        W: 'w + Write,
{
    type Ok = ();
    type Error = DeError;

    fn serialize_field<T: ?Sized + Serialize>(
        &mut self,
        key: &'static str,
        value: &T,
    ) -> Result<(), DeError> {
        let type_name = std::any::type_name::<T>();
        let is_attr = is_basic_type(type_name);
        println!{"type_name {}", type_name};
        if is_attr {
            write!(self.parent.writer.inner(), " ").map_err(Error::Io)?;
            key.serialize(&mut *self.parent)?;
            write!(self.parent.writer.inner(), "=").map_err(Error::Io)?;

            write!(self.parent.writer.inner(), r#"""#).map_err(Error::Io)?;
            value.serialize(&mut *self.parent)?;
            write!(self.parent.writer.inner(), r#"""#).map_err(Error::Io)?;
            self.attrs += 1;
        } else {
            let key = self.name.as_bytes();
            if self.needs_close {
                write!(self.parent.writer.inner(), ">").map_err(Error::Io)?;
                self.needs_close = false;
            }
            value.serialize(&mut *self.parent)?;
        }

        Ok(())
    }

    fn end(self) -> Result<Self::Ok, DeError> {
        if self.needs_close {
            write!(self.parent.writer.inner(), ">").map_err(Error::Io)?;
        }
        write!(self.parent.writer.inner(), "</").map_err(Error::Io)?;
        self.name.serialize(&mut *self.parent)?;
        write!(self.parent.writer.inner(), ">").map_err(Error::Io)?;
        Ok(())
    }
}
```

Example output:

```
running 2 tests

original XML 
<Outer dummy="10" foo="bar">
	<inner in_dummy="30">
	</inner>
</Outer>

original XML 
<Outer>
	<inner in_dummy="30">
	</inner>
</Outer>

outer Test2 { inner: Inner { in_dummy: 30 } }
type_name test_xml::Inner
type_name u32

serialized "<Test2><Inner in_dummy=\"30\"></Inner></Test2>"

test tests::xml_parse_test_2 ... ok

outer Outer { dummy: 10, foo: "bar", inner: Inner { in_dummy: 30 } }
type_name u32
type_name alloc::string::String
type_name test_xml::Inner
type_name u32
serialized "<Outer dummy=\"10\" foo=\"bar\"><Inner in_dummy=\"30\"></Inner></Outer>"

test tests::xml_parse_test_1 ... ok
test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by crusty-dave** [comment] 2020-03-25 22:50
Here is the test code for the above test:

```
#[macro_use] extern crate serde_derive;

use serde::ser::{Serialize, Serializer, SerializeStruct, SerializeSeq};

use quick_xml::{
    de::{from_str},
    se,
};

#[derive(Debug, Serialize, Deserialize, PartialEq, Default)]
struct Inner {
    in_dummy: u32
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Default)]
struct Outer {
    dummy: u32,
    foo: String,
    inner: Inner,
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Default)]
struct Test2 {
    inner: Inner,
}

/*
impl Serialize for Outer {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: Serializer,
    {
        // 3 is the number of fields in the struct.
        let mut state = serializer.serialize_struct( "Outer", 3)?;
        state.serialize_field("dummy", &self.dummy)?;
        state.serialize_field("foo", &self.foo)?;
        state.serialize_field("inner", &self.inner)?;
        state.end()
    }
}
*/

fn main() {
}


#[cfg(test)]
mod tests {
    use super::*;

    const TEST_XML_1: &str =
r#"
<Outer dummy="10" foo="bar">
	<inner in_dummy="30">
	</inner>
</Outer>
"#;

    const TEST_XML_2: &str =
r#"
<Outer>
	<inner in_dummy="30">
	</inner>
</Outer>
"#;

    #[test]
    fn xml_parse_test_1()
    {
        println!{};
        println!{"original XML {}", TEST_XML_1};
        println!{};

        let outer: Outer = match from_str(TEST_XML_1) {
            Ok(foo) => foo,
            Err(e) => {
                println!{"deserialize error {:?}", e};
                assert!{false};
                return;
            }
        };

        println!{"outer {:?}", &outer};
        println!{};

        let xml2 = match se::to_string(&outer) {
            Ok(xml2) => xml2,
            Err(e) => {
                println!{"serialize error {:?}", e};
                assert!{false};
                return;
            }
        };
        println!{"serialized {:?}", &xml2};
        println!{};
    }

    #[test]
    fn xml_parse_test_2()
    {
        println!{};
        println!{"original XML {}", TEST_XML_2};
        println!{};

        let outer: Test2 = match from_str(TEST_XML_2) {
            Ok(foo) => foo,
            Err(e) => {
                println!{"deserialize error {:?}", e};
                assert!{false};
                return;
            }
        };

        println!{"outer {:?}", &outer};
        println!{};

        let xml2 = match se::to_string(&outer) {
            Ok(xml2) => xml2,
            Err(e) => {
                println!{"serialize error {:?}", e};
                assert!{false};
                return;
            }
        };
        println!{"serialized {:?}", &xml2};
        println!{};
    }
}
```

**Comment by crusty-dave** [comment] 2020-03-25 23:32
As I state earlier, to solve this correctly, there should probably be two Vecs, one for the attributes and one for the children.

serialize_field() would need to collect the Vecs, then end() would serialize the result.

The problem with that is Serialize cannot be used to create a trait object.

If someone wanted to integrated the erased-serde crate, they could probably make that work.

In the meantime, the code that I provided above does seem to be working for my larger test case where I originally found the problem.  If anyone else wants to use it, just remember that you need any attributes declared in a struct to be declared before any other embedded structs.

**Comment by crusty-dave** [comment] 2020-03-26 00:16
@tafia Any chance that you would be willing to merge my fix above into a new 0.18.2?

It isn't an ideal fix, but it works better than the current code, which doesn't work at all.

Regards,
-Dave

**Comment by crusty-dave** [comment] 2020-03-27 01:26
I have created a fork, and I have fixed the unit tests, however, there seem to be a lot of other tests that are current failing not related to serialize.

cargo test --features serialize

test test_writer_indent ... FAILED

test sample_1_full ... FAILED
test sample_1_short ... FAILED
test sample_2_full ... FAILED
test sample_2_short ... FAILED
test sample_ns_short ... FAILED

**Comment by crusty-dave** [comment] 2020-03-27 02:18
I have created a pull request with the fix.

I added 4 new tests.

running 7 tests
test se::tests::test_serialize_enum ... ok
test se::tests::test_serialize_map_entries ... ok
test se::tests::test_serialize_bool ... ok
test se::tests::test_serialize_struct ... ok
**test se::tests::test_serialize_struct_complex_outer ... ok**
test se::tests::test_serialize_struct_field ... ok
**test se::tests::test_serialize_struct_nested ... ok**

test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 20 filtered out

running 2 tests
**test tests::test_serialize_deserialize_struct_nested ... ok
test tests::test_serialize_deserialize_struct_complex_outer ... ok**

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

**Comment by mlevkov** [comment] 2020-03-30 04:38
@crusty-dave This looks awesome and very promising. However, I think there is got to be a way to mark which fields are attributes and which ones are not. I'm not that verse in Rust yet to discern whether your approach is considered of such. Please let me know.

**Comment by crusty-dave** [comment] 2020-03-30 23:21
@mlevkov refer to my comment [Issue 205](https://github.com/tafia/quick-xml/pull/205#issuecomment-605680462).

The current solution depends on the following to determine if it is an attribute or another child struct.

```
fn is_basic_type(type_name: &str) -> bool {
    match type_name {
        "bool" | "char" | "option" | "()" => true,
        "u8" | "u16" | "u32" | "u64" | "u128" => true,
        "i8" | "i16" | "i32" | "i64" | "i128" => true,
        "f32" | "f64" => true,
        "[u8]" => true,
        "alloc::string::String" => true,
        _ => false
    }
}
```

It would probably be helpful to specify an attribute with a tag of some sort, but barring that, this was the simplest solution that I came up with.  It might still be missing some types that could still be considered attributes.

**Comment by tafia** [comment] 2020-03-31 02:20
There doesn't seem to be an easy way to handle it via serde attributes.

Alternatively we could specify this kind of information when serializing. 
```rust
let xml = quick_xml::se::to_string(value, Some(my_se_params)); // need to figure out what struct works best for SeParams
```

**Comment by rlustin** [comment] 2020-03-31 08:31
Hi! I’m quite interested in this feature too.

What’s about using serde rename field, like the library do with `$value`, but a bit more complex? Something like:

```rust
#[serde(rename = "$xml:attr:name")] 
```

**Comment by mlevkov** [comment] 2020-04-08 06:53
any further consideration on this topic?

**Comment by crusty-dave** [comment] 2020-04-08 07:06
I have moved on to using crate **xmltree**, my fix isn't ideal, but it works as long as children are always specified after all attributes when declaring the struct.

As I state earlier, to solve this correctly, there should probably be two Vecs (of serde trait objects), one for the attributes and one for the children.

serialize_field() would need to collect into one of the two Vecs, then end() would serialize the result.

The problem with that is Serialize cannot be used to create a trait object.

If someone wanted to integrate the **erased-serde** crate, they could probably make it work using trait objects stored into the two Vecs (Vec<attr traits> Vec<child traits>..

**Comment by huaoguo** [comment] 2020-06-27 07:52
See if #221 fixes this

**Comment by SirWindfield** [comment] 2021-01-31 00:04
Even though it now works for basic types, I think this isn't ideal. Some scenarios might call for basic type serialisation as xml child elements instead of attributes. I think a good long-term solution would be to either introduce some custom syntax around `serde::rename` (already mentioned above) or to introduce a custom new attribute that people have to use to make the field an attribute (`#[xml(type = "attribute | item")]`). 

I am currently trying to read and write an XML file that has simple types as items and that the current implementation does fail because it assumes that those types are alway attributes.

I can work around it with a custom serializer, but that is far from ideal.

**Comment by Mingun** [comment] 2022-05-21 21:36
Duplicate of #293

**Closed by Mingun** 2022-05-21 21:36 UTC
Labels: enhancement, serde
