### ISSUE TITLE
Is it currently possible to get attribute value from &str without copying?

### ISSUE THREAD

**Issue by gwy15** [tafia/quick-xml#726] opened 2024-03-11 10:01 UTC
Hi,
I plan to use quick-xml to parse heavy work loads and I want to make overheads (copying of strings and allocations) as little as possible.
My work load includes parsing millions of lines of xml and extracting specific fields from them, but I can't extract attribute value from a slice of str without copying it. Is it currently possible to do so? Thank you!

```rust
/// gets the "value" from <root key="value"></root>
fn parse<'s>(s: &str) -> Option<Cow<'s, str>> {
    let mut reader = quick_xml::Reader::from_str(s);
    loop {
        let event = reader.read_event().unwrap();
        match event {
            Event::Start(start) if start.name().0 == b"root" => {
                // start: BytesStart<'s>
                let attr: Attribute<'s> = start.try_get_attribute("key").unwrap()?;
                // ^^^^^^^^^^^^^^^^^^^^ But I can only get Attribute<'start> here, not Attribute<'s>
                // and cannot return Cow<'s, str> without making an owned string.
                break attr.unescape_value().ok();
            }
            Event::End(end) if end.name().0 == b"root" => {
                break None;
            }
            _ => {}
        }
    }
}
```

**Comment by Mingun** [comment] 2024-03-11 16:09
Probably this is impossible now. I'll close this as duplicate of #332

**Closed by Mingun** 2024-03-11 16:09 UTC
