### ISSUE TITLE
Serialization of adjacently tagged enums

### ISSUE THREAD

**Issue by allsey87** [tafia/quick-xml#225] opened 2020-07-28 10:00 UTC
Considering the following enum to be serialized using the adjacently tagged method:
```rust
#[derive(Serialize, Deserialize)]
#[serde(tag = "tag", content = "content")]
enum EType {
    TsInteger{ival: i32},
    TsString{sval: String},
}
```
I would expect that the output for `EType::TsInteger{ival: 6}` would be:
```xml
<EType>
   <tag>TsInteger</tag>
   <content>
      <ival>6</ival>
   </content>
</EType>
```
However, I am getting:
```xml
<EType>
   <tag>TsInteger</tag>
   <content>
      <TsInteger>
         <ival>6</ival>
      </TsInteger>
   </content>
</EType>
```
Is this a bug or have I misunderstood something here?

**Comment by tafia** [comment] 2020-07-31 08:33
I might be a bug, these are corner case I didn't particularly looked at.

**Comment by Mingun** [comment] 2020-10-11 14:34
This is duplicate of #204

**Closed** 2020-10-17 02:41 UTC
