### ISSUE TITLE
Members of flattened structs are not converted

### ISSUE THREAD

**Issue by allsey87** [tafia/quick-xml#226] opened 2020-07-29 08:14 UTC
The following working example reproduces the problem. In a nutshell, there seems to be a problem with converting strings to the types inside `struct Inner` but only when it is flattened into `struct Outer`. These flattened members are unable to be parsed into booleans, integers etc.
```rust
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Inner {
	left: i32,
	right: i32,	
}

#[derive(Debug, Deserialize)]
struct Outer {
	name: String,

	#[serde(flatten)]
	inner: Inner,
}

fn main() {
	let pass = r#"<inner left="1" right="2" />"#;
	let fail = r#"<outer name="foo" left="1" right="2" />"#;

	println!("{:?}", quick_xml::de::from_str::<Inner>(&pass));
	println!("{:?}", quick_xml::de::from_str::<Outer>(&fail));
}
```
This prints:
```
Ok(Inner { left: 1, right: 2 })
Err(Custom("invalid type: string \"1\", expected i32"))
```
Deserialization of `struct Outer` only works when `left` and `right` are `String`. In this case, the output is:
```
Ok(Inner { left: "1", right: "2" })
Ok(Outer { name: "foo", inner: Inner { left: "1", right: "2" } })
```

**Comment by allsey87** [comment] 2020-07-29 08:22
It seems `serde_xml_rs` also falls over in the exact same way... Is this a limitation of serde perhaps?

**Comment by tafia** [comment] 2020-07-29 08:51
I didn't check this. I believe it is not a serde issue. I do not have lot of time to fix it, would you want to give it a try?

**Comment by allsey87** [comment] 2020-07-29 10:45
I had a very quick look but also have very little time. The error is generated during visiting a map here: https://github.com/tafia/quick-xml/blob/master/src/de/mod.rs#L268

Looking at the error:
```
Err(Custom("invalid type: string \"1\", expected i32"))
```
Perhaps the there is an extract layer of quotation marks around the integer in the map which is preventing the conversion to an integer?

**Comment by allsey87** [comment] 2020-07-29 11:08
I tracked the error as far as: https://github.com/tafia/quick-xml/blob/master/src/de/map.rs#L87

Looking at the `Vec<u8>` passed to `EscapedDeserializer` there doesn't appear to be a difference between the two cases which is strange. Printing those `u8`'s using `std::str::from_utf8` gave `1` and `2`  in both cases (with/without nesting) and without any additional `"` characters...

**Comment by allsey87** [comment] 2020-07-30 09:30
Digging deeper. I have switched from integers to booleans since it is easier to track them in the code (since there are several helper macro's around integers).

It seems, for some reason, in the first (working case) serde parses the `true` or `false` by calling `deserializer.deserialize_bool` [from here](https://github.com/serde-rs/serde/blob/v1.0.114/serde/src/de/impls.rs#L78) and in the second (not working case) where inner has been flattened into outer, serde parses the `true` or `false` by calling `deserializer.deserialize_any` [from here](https://github.com/serde-rs/serde/blob/v1.0.114/serde/src/private/de.rs#L317) which you delegate to `deserialize_str`.

Any input from your side? I am pretty sure you are more knowledge on all of this than I am.

**Comment by allsey87** [comment] 2020-07-30 09:38
Probably the most notable difference between the two cases that I have seen so far is that, right at the beginning, when there is no structure flattening, serde calls `deserialize_struct` while when there is structure flattening, serde calls `deserialize_map` which you delegate to `deserialize_struct` with an empty string as its name...

**Comment by Mingun** [comment] 2020-08-28 19:06
This is longstanding serde bug/poor flatten design: https://github.com/serde-rs/serde/issues/1529, https://github.com/serde-rs/serde/issues/1183

**Comment by tobz1000** [comment] 2020-09-19 18:26
I've detailed my workaround on the `serde-xml-rs` bug, which others might find helpful: https://github.com/RReverser/serde-xml-rs/issues/137#issuecomment-695341295

**Comment by fwcd** [comment] 2021-05-02 17:53
This applies to internally tagged enums too, consider the following definition:

```rust
#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "type")]
enum Tagged {
    A { x: i32 },
    B { y: String },
}
```

Trying to parse `<Tagged type="A" x="32"/>` fails with

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("invalid type: string \"32\", expected i32")'
```

**Comment by Mingun** [comment] 2022-05-21 21:12
Duplicate of #286. As explained there, there are nothing that we can do

**Closed by Mingun** 2022-05-21 21:12 UTC
