### ISSUE TITLE
Feature request: allow to use `partial_escape` when serializing structs

### ISSUE THREAD

**Issue by Alexis211** [tafia/quick-xml#350] opened 2022-01-12 07:14 UTC
Here is the definition of a struct I want to serialize:

```rust
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct Value(#[serde(rename = "$value")] pub String);

#[derive(Debug, Serialize, PartialEq)]
pub struct CopyPartResult {
	#[serde(rename = "LastModified")]
	pub last_modified: Value,
	#[serde(rename = "ETag")]
	pub etag: Value,
}
```

Here is a test value for serialization:

```rust
let v = CopyPartResult {
	last_modified: Value("2011-04-11T20:34:56.000Z".into()),
	etag: Value("\"9b2cf535f27731c974343645a3985328\"".into()),
};
```

I want `quick_xml::se::to_string` to return the following XML:

```xml
<CopyPartResult><LastModified>2011-04-11T20:34:56.000Z</LastModified><ETag>"9b2cf535f27731c974343645a3985328"</ETag></CopyPartResult>
```

Currently, it returns the following result where `"` is escaped as `&quot;` (I don't want that):

```xml
<CopyPartResult><LastModified>2011-04-11T20:34:56.000Z</LastModified><ETag>&quot;9b2cf535f27731c974343645a3985328&quot;</ETag></CopyPartResult>
```

I saw in the codebase that there is a `partial_escape` function (comming in 0.23) that can be used to not escape quotes, however it seems that there is no way to use that for struct fields. It would be nice if I could write something like this:

```rust
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct Value(#[serde(rename = "$value", escape_with = "quick_xml::escape::partial_escape")] pub String);
```

Thanks!

**Comment by Mingun** [comment] 2022-06-05 17:56
Duplicate of #362

**Closed by Mingun** 2022-06-05 17:56 UTC
Labels: enhancement, serde
