### ISSUE TITLE
equivalent to `serde_json::value::RawValue`

### ISSUE THREAD

**Issue by enricozb** [tafia/quick-xml#698] opened 2024-01-03 19:03 UTC
## Question

Is there any equivalent to `serde_json::value::RawValue`? Specifically, I want to capture the contents of a tag as literal XML into a `String` (or `Vec<u8>` or `&[u8]`). I don't care about validating or parsing the inner XML format.

An example of code I would expect to work would be:
```rust
const xml: &str = r#"
  <who-cares>
    <foo>
      <bar></bar>
    </foo>
  </who-cares>
"#;

#[derive(Deserialize, Debug)]
struct Root<'a> {
  #[serde(borrow, rename = "$value")]
  field: &'a quick_xml::RawValue,
}

let root = quick_xml::de::from_str::<Root>(&xml).unwrap();

println!("parsed: {root:?}");
```

And after parsing `root.field` would contain as bytes or as a utf8 string `"<foo><bar></bar></foo>"` (spaces stripped or not stripped, doesn't really matter).

Is there any way to do this?

## Motivation
I have some XML that contains HTML-like data in some tags, like this:
```xml
<item>
  <name>Some Item</name>
  <description>This is a <i>vintage</i> something <b>or</b> other.</description>
</item>
```
Notice that `item.description` contains HTML-like markup, and I want to pass around that string opaquely through my application.

**Comment by Mingun** [comment] 2024-01-03 21:03
Yes, this is essentially a duplicate of #257

**Closed by Mingun** 2024-01-03 21:03 UTC
Labels: duplicate, enhancement, serde
