### ISSUE TITLE
UnexpectedEnd([80, 97, 114, 116, 84, 121, 112, 101])

### ISSUE THREAD

**Issue by shenjackyuanjie** [tafia/quick-xml#564] opened 2023-02-25 07:05 UTC
I try to use quick-xml to deserialize [this](https://github.com/shenjackyuanjie/Difficult-Rocket/blob/eed5a7460c35aaa7f7af94a52c79f9c8c1d23689/configs/PartList.xml) xml file 
but it gives me this
![image](https://user-images.githubusercontent.com/54507071/221343805-33acbcad-7146-4e5b-9b26-36f9cf609c6b.png)

code at here
https://github.com/shenjackyuanjie/Difficult-Rocket/blob/eed5a7460c35aaa7f7af94a52c79f9c8c1d23689/libs/Difficult_Rocket_rs/src/src/sr1_data.rs

**Comment by Mingun** [comment] 2023-02-25 08:13
Duplicate of #510

**Closed by Mingun** 2023-02-25 08:13 UTC
Labels: bug, duplicate, serde, arrays
