### ISSUE TITLE
Access to the escaped $value

### ISSUE THREAD

**Issue by bilelmoussaoui** [tafia/quick-xml#229] opened 2020-08-12 01:31 UTC
I have a use case of an xml file that's used widely to describe Linux components to software centers called Appstream which I'm writing a parser & wrapper for using quick-xml.

The spec has a  description tag that looks like this 
```xml
    <description>
        <p>
      Debian is a free operating system (OS) for your computer.
      An operating system is the set of basic programs and utilities that make your computer run.
        </p>
    </description>
```
If you do use `$value`  my code won't compile as there are multiple values (if the description has multiple or nested tags like ul/li).

Other suggestions to handle such use case would be very welcome as implementing my own deserialize can't work or I didn't manage to figure out what's needed

**Comment by tafia** [comment] 2020-09-24 07:20
Hey, sorry for the late answer. I am not sure I understand you're issue. Do you have a full example you want to deserialize?

**Comment by bilelmoussaoui** [comment] 2020-09-24 10:10
No worries :) 
Here's the actual xml file I'm trying to parse 
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2013 First Lastname <your@email.com> -->
<component type="desktop-application">
    <id>org.gnome.gnome-power-statistics</id>
    <metadata_license>FSFAP</metadata_license>
    <project_license>GPL-2.0+</project_license>
    <name>Power Statistics</name>
    <summary>Observe power management</summary>

    <description>
        <p>
      Power Statistics is a program used to view historical and current battery
      information and will show programs running on your computer using power.
        </p>
        <p>Example list:</p>
        <ul>
            <li>First item</li>
            <li>Second item</li>
        </ul>
        <p>
      You probably only need to install this application if you are having problems
      with your laptop battery, or are trying to work out what programs are using
      significant amounts of power.
        </p>
    </description>

    <launchable type="desktop-id">org.gnome.gnome-power-statistics.desktop</launchable>

    <screenshots>
        <screenshot type="default">
            <caption>The options dialog</caption>
            <image type="source">http://www.hughsie.com/en_US/main.png</image>
        </screenshot>
        <screenshot>
            <image type="source">http://www.hughsie.com/en_US/preferences.png</image>
        </screenshot>
    </screenshots>

    <url type="homepage">http://www.gnome.org/projects/en_US/gnome-power-manager</url>
    <project_group>GNOME</project_group>

    <provides>
        <binary>gnome-power-statistics</binary>
        <id>gnome-power-statistics.desktop</id>
    </provides>

    <releases>
        <release version="3.12.2" date="2013-04-12">
            <description>
                <p>Fixes issues X, Y and Z</p>
            </description>
        </release>
    </releases>
</component>
```

As you can see, the description tags can contain markup (<p>, <ul>, <ol>, <li> & probably other tags). What I would like to be able to deserialize the content of description as a String that will contain 
```
 <p>
      Power Statistics is a program used to view historical and current battery
      information and will show programs running on your computer using power.
        </p>
        <p>Example list:</p>
        <ul>
            <li>First item</li>
            <li>Second item</li>
        </ul>
        <p>
      You probably only need to install this application if you are having problems
      with your laptop battery, or are trying to work out what programs are using
      significant amounts of power.
        </p>
```

**Comment by Mingun** [comment] 2022-05-21 21:05
Duplicate of #257

**Closed by Mingun** 2022-05-21 21:05 UTC
Labels: enhancement, serde
