### ISSUE TITLE
A error in deserialization not report line or source of error?

### ISSUE THREAD

**Issue by mamcx** [tafia/quick-xml#224] opened 2020-07-02 23:23 UTC
I'm deserializing a huge xml file. Then I get a error like:

`XMLError { source: Custom("invalid type: map, expected a Decimal type representing a fixed-point number") }`

Very well.... but what cause it? The data or line that cause the error is not provided, so I'm lost to check what to fix (and this could be displayed to end users, is a ETL operation)

**Comment by tafia** [comment] 2020-07-17 03:26
In general you can use the `Reader::buffer_position` to know where you are but I believe you're using serde and indeed it is not supported today, we should probably enhance the returned error type in that case.

**Comment by Mingun** [comment] 2022-05-21 21:15
Duplicate of #313

**Closed by Mingun** 2022-05-21 21:15 UTC
Labels: enhancement, serde
