### ISSUE TITLE
what's BytesStart::unescaped for?

### ISSUE THREAD

**Issue by scottlamb** [tafia/quick-xml#341] opened 2021-11-13 00:16 UTC
I'm trying to switch to `quick-xml` and am struggling to understand the API for just getting strings (for tag names, attribute names, attribute values, and text/cdata nodes).

I saw that the caller must unescaped text/cdata/attribute values, and [this comment](https://github.com/tafia/quick-xml/issues/158#issuecomment-529355417) that the caller must decode the character encoding.

Next question: what is [`BytesStart::unescaped`](https://docs.rs/quick-xml/0.22.0/quick_xml/events/struct.BytesStart.html#method.unescaped) for? It says it handles escapes/entities like `&lt;` but that doesn't make sense to me. Is this the right grammar for the XML tag name from the [spec](https://www.w3.org/TR/xml/#sec-common-syn)?

```text
NameStartChar ::= ":" | [A-Z] | "_" | [a-z] | [#xC0-#xD6] | [#xD8-#xF6] | [#xF8-#x2FF] | [#x370-#x37D] | [#x37F-#x1FFF] | [#x200C-#x200D] | [#x2070-#x218F] | [#x2C00-#x2FEF] | [#x3001-#xD7FF] | [#xF900-#xFDCF] | [#xFDF0-#xFFFD] | [#x10000-#xEFFFF]
NameChar ::= NameStartChar | "-" | "." | [0-9] | #xB7 | [#x0300-#x036F] | [#x203F-#x2040]
Name ::= NameStartChar (NameChar)*
```

It looks like a `&` (aka `#x26`) isn't allowed. So why unescape? or what am I missing?

**Comment by Mingun** [comment] 2022-05-25 15:50
Actually, that method gives you all internal content of a tag (i.e. name + attributes). As such, it could have been intended in order to expand entities in all attributes in one pass. Probably we should remove it and provide other ways to get normalized attribute value (see also #371)

**Comment by Mingun** [comment] 2022-05-25 17:09
Duplicate of #118

**Closed by Mingun** 2022-05-25 17:09 UTC
Labels: help wanted

**Comment by kornelski** [comment] 2022-06-17 19:39
I suggest to deprecate or remove this method. I don't see any valid use for it. Entities are not allowed in tag names, and unescaping of attributes as a whole allows injection:

```xml
<foo real="1&quot; fake=&quot;2"/>
```

unescapes to:

```xml
<foo real="1" fake="2"/>
```
