### ISSUE TITLE
How to ignore double quotation mark when do serialization？

### ISSUE THREAD

**Issue by ewenliu** [tafia/quick-xml#362] opened 2022-02-18 10:25 UTC
Before serialization:

r#""349DC700140D7F86A0784842780****""

After serialization:
> &quot349DC700140D7F86A0784842780****&quot

However, What expect:
"349DC700140D7F86A0784842780****"

How to ignore serializing double quotation mark?

**Comment by Mingun** [comment] 2022-05-07 18:08
That is impossible now. In my fork, https://github.com/Mingun/fast-xml, I'll plan to implement API for set desired level of quoting:

```rust
enum QuoteLevel {
  /// - `<` -> `&lt;`
  /// - `>` -> `&gt;`
  /// - `&` -> `&amp;`
  /// - `"` -> `&quot;`
  /// - `'` -> `&apos;`
  Full,
  /// - `<` -> `&lt;`
  /// - `>` -> `&gt;`
  /// - `&` -> `&amp;`
  Partial,
  /// - `<` -> `&lt;`
  /// - `&` -> `&amp;`
  Minimal,
}
let mut s = Serializer::new(...);
s.set_quote_level(QuoteLevel::Minimal);
...
```

**Comment by Mingun** [comment] 2022-06-05 14:41
This requires a bit more work than I expect initially. `BytesText` and `BytesStart` both contains already escaped content, so to implement proposed API for serializer and at the same time to avoid unnecessary decode-encode roundtrip it is necessary to rework an API.

I think, it is needed to split `Event` into `reader::Event` and `writer::Event`:
- `reader::Event` will store _escaped_ content, as presented in a parsed stream. Current `Event` could be converted to `reader::Event` with minimal changes. Probably, storing `Cow` inside will no longer be needed
- `writer::Event` will store _unescaped_ content and therefore could be writted with desired level of escaping

**Comment by dralley** [comment] 2022-06-05 15:38
It's possible with the non-serde API 

```
            //  <changelog author="dalley &lt;dalley@redhat.com&gt; - 2.7.2-1" date="1251720000">- Update to 2.7.2</changelog>
            self.writer
                .create_element(TAG_CHANGELOG)
                .with_attribute(("author", changelog.author.as_str()))
                .with_attribute(("date", changelog.date.to_string().as_str()))
                .write_text_content(BytesText::from_escaped(partial_escape(
                    &changelog.description.as_bytes(),
                )))?;
```

**Comment by dralley** [comment] 2022-06-05 15:51
This is possible to do with the non-serde raw API.

```
use quick_xml::{Writer, events::Event, events::BytesDecl, events::BytesText, events::BytesStart, escape::partial_escape};
use std::fs::File;
use std::io::Cursor;
use std::io::Write;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut writer = Writer::new_with_indent(Cursor::new(Vec::new()), b' ', 2);
    writer.write_event(Event::Decl(BytesDecl::new(b"1.0", Some(b"UTF-8"), None)))?;
    writer.create_element("test").write_text_content(BytesText::from_escaped(r#""349DC700140D7F86A0784842780****""#.as_bytes()))?;

    print!("{}", std::str::from_utf8(&writer.into_inner().into_inner())?);

    Ok(())
}

```

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `target/debug/playground`
<?xml version="1.0" encoding="UTF-8"?>
<test>"349DC700140D7F86A0784842780****"</test>
```

**Comment by dralley** [comment] 2022-06-05 16:17
Also this issue seems like a duplicate of https://github.com/tafia/quick-xml/issues/350

**Comment by Mingun** [comment] 2022-06-05 17:56
Yeah, initially I thought, that I probably could provide a function for `#[serde(serialize_with)]`, but it seems unnecessary to introduce it at quick-xml level. I doubt that someone will needed in different rules when serializing different fields. I'll close #350 as duplicate, because here a more info

**Comment by Xuanwo** [comment] 2022-08-25 09:28
> Yeah, initially I thought, that I probably could provide a function for `#[serde(serialize_with)]`, but it seems unnecessary to introduce it at quick-xml level.

Any updates on this? I met the same problem here (Yes, aws s3 again).

I tried to use `serialize_with` with `partial_escape` but it doesn't works:

```rust
#[derive(Default, Debug, Serialize)]
#[serde(default, rename_all = "PascalCase")]
struct CompleteMultipartUploadRequestPart {
    #[serde(rename = "$unflatten=PartNumber")]
    part_number: usize,
    #[serde(rename = "$unflatten=ETag", serialize_with = "partial_escape")]
    etag: String,
}

fn partial_escape<S>(s: &str, ser: S) -> std::result::Result<S::Ok, S::Error>
where
    S: serde::Serializer,
{
    ser.serialize_str(&String::from_utf8_lossy(
        &quick_xml::escape::partial_escape(s.as_bytes()),
    ))
}
```

`partial_escape` produces the expected results. But after serialize, we still got escape content. Seems `quick-xml` does escape at another level.

**Comment by Mingun** [comment] 2022-08-25 10:10
As a quick fix I could suggest to change quick-xml locally and build with the patched version. You should make changes here:
https://github.com/tafia/quick-xml/blob/be8138f26c4a98251813cd05ef45abef9531a589/src/se/mod.rs#L98-L111
```diff
-            BytesText::new(&value)
+            BytesText::from_escaped(&crate::escape::partial_escape(&value))
```

**Comment by Mingun** [comment] 2022-09-06 18:42
I should say, that quick fix, suggested above, will not work correctly in all cases. This code writes also attribute values and avoiding escape `"` will produce incorrect results if attribute value will contain `"`. Good news that I've almost done new serializer which will have the mentioned setting

**Closed** 2023-11-25 18:50 UTC
Labels: enhancement, help wanted, serde
