### ISSUE TITLE
How to avoid deserializing certain XML elements (like HTML tags) and return as String

### ISSUE THREAD

**Issue by Zenleaf** [tafia/quick-xml#241] opened 2020-11-07 07:19 UTC
Hi there, I have the following XML that I would like to deserialize using Quick-Xml and Serde. It is part of a very large, nested XML structure.
```xml
<AbstractText Label="Results" NlmCategory="UNASSIGNED">
  We found that neonatal mortality was significantly associated with neonatal prematurity (p = 0.013), IUGR 
  <mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML">
      <mml:mo>&lt;</mml:mo>
  </mml:math> 0.001), placental pathology (p = 0.04), we had no maternal mortality.
</AbstractText>
```
I want to deserialize the above into the following struct:
```rust
#[derive(Debug, Deserialize, PartialEq)]
pub struct AbstractText {
    #[serde(rename = "Label", default)]
    pub label: String,

    #[serde(rename = "NlmCategory", default)]
    pub nlm_category: String,

    #[serde(rename = "$value")]
    pub text: String,
}
```
As you can see the `$value` of `<AbstractText>`  has some `<mml:math>` tags and occasionally will have some HTML tags.
I would like to have those tags deserialized to String. So `"<mml:math>"` must be stringiified as is.

How can I go about doing this? Currently I get ``Error: Start`` when trying to deserialize this.

**Comment by Mingun** [comment] 2022-05-21 20:52
Duplicate of #383

**Closed by Mingun** 2022-05-21 20:52 UTC
Labels: enhancement, serde
