### ISSUE TITLE
Deserializing a struct with a `flatten`ed child with attributes and element children results in error `invalid type: map, expected a string`

### ISSUE THREAD

**Issue by nikitawootten** [tafia/quick-xml#637] opened 2023-08-20 19:00 UTC
I've been running into an issue deserializing structs with flattened children containing attribute and element fields.

Given 2 structs, one with attribute and element children, and the other containing the flattened first struct:
```rust
// The important thing is that the child struct contains both an attribute and an element field
#[derive(serde::Deserialize, serde::Serialize)]
struct SimpleStruct {
    #[serde(rename = "@attr")]
    attr: String,

    child: String,
}

#[derive(serde::Deserialize, serde::Serialize)]
struct StructWithFlattenedChild {
    #[serde(flatten)]
    flattened: SimpleStruct,

    // The struct could also contain other fields...
}
```

The simple struct can be deserialized without issue:
```rust
#[test]
fn deserialize_simple_struct() {
    quick_xml::de::from_str::<SimpleStruct>(
        r#"<Test attr="a">
                <child>b</child>
            </Test>"#,
    ).unwrap();
}
```

```
test test::deserialize_simple_struct ... ok
```

However deserializing the other struct with the same data produces an error:
```rust
#[test]
fn deserialize_struct_with_flattened_child() {
    quick_xml::de::from_str::<StructWithFlattenedChild>(
        r#"<Test attr="a">
                <child>b</child>
            </Test>"#,
    ).unwrap();
}
```

```
thread 'definition::test::deserialize_struct_with_flattened_child' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("invalid type: map, expected a string")', src/test.rs:14:6
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /build/rustc-1.70.0-src/library/core/src/result.rs:1089:23
   4: example::test::deserialize_struct_with_flattened_child
             at ./src/test.rs:9:5
   5: example::test::deserialize_struct_with_flattened_child::{{closure}}
             at ./src/test.rs:8:46
   6: core::ops::function::FnOnce::call_once
             at /build/rustc-1.70.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test test::deserialize_struct_with_flattened_child ... FAILED

failures:

failures:
    test::deserialize_struct_with_flattened_child
```

<details>
    <summary>Full code snippet</summary>

    #[derive(serde::Deserialize, serde::Serialize)]
    struct StructWithFlattenedChild {
        #[serde(flatten)]
        flattened: SimpleStruct,
    }

    #[test]
    fn deserialize_struct_with_flattened_child() {
        quick_xml::de::from_str::<StructWithFlattenedChild>(
            r#"<Test attr="a">
                    <child>b</child>
                </Test>"#,
        )
        .unwrap();
    }

    #[derive(serde::Deserialize, serde::Serialize)]
    struct SimpleStruct {
        #[serde(rename = "@attr")]
        attr: String,

        child: String,
    }

    #[test]
    fn deserialize_simple_struct() {
        quick_xml::de::from_str::<SimpleStruct>(
            r#"<Test attr="a">
                    <child>b</child>
                </Test>"#,
        )
        .unwrap();
    }
</details>

Additional info:
* Quick-XML v0.30.0
* Serde v1.0.183

**Comment by Mingun** [comment] 2023-08-20 19:38
Duplicate of #226.

**Closed by Mingun** 2023-08-20 19:38 UTC
Labels: duplicate, serde
