### ISSUE TITLE
`None` values serialize as empty element and fail round trip deserializing

### ISSUE THREAD

**Issue by hfiguiere** [tafia/quick-xml#636] opened 2023-08-20 15:47 UTC
```rust
#[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
#[serde(rename = "results")]
pub struct Results {
    #[serde(default)]
    pub raw_type_id: Option<u32>,
}

let r = Results { raw_type_id: None };
```

Serializing `r` will output:
```xml
<results>
<raw_type_id />
</results>
```

Deserializing the xml will fail with:
```
thread 'tests::deser' panicked at 'deserialize: InvalidInt(ParseIntError { kind: Empty })', src/lib.rs:133:45
```

So round trip serialization fails.

However
```xml
<results>
</results>
```

Will be sucessful and equal to
```rust
Results { raw_type_id: None }
```

Note: `serde_xml_rs` has similar issues.

I have two expectations here:
1. that None value be allowed to not generate an empty element. This would work around the serialization error.
2. the an empty element desrialization works for the underlying type is `Option<>` and then yield None.

Unless I'm misunderstanding how this is supposed to work, but round trip defintely fails.

**Comment by hfiguiere** [comment] 2023-08-20 16:05
Probably the same as #497

**Comment by Mingun** [comment] 2023-08-20 17:25
Yes, this is duplicate of #497

**Closed by Mingun** 2023-08-20 17:25 UTC
