### ISSUE TITLE
Unexpected Bang Since 0.23.1

### ISSUE THREAD

**Issue by JojiiOfficial** [tafia/quick-xml#590] opened 2023-04-11 15:48 UTC
The following file can't be parsed since 0.23.1 as it throws an UnexpectedBang(69) when parsing with the given example code. Simply ignoring the error causes the given example code not to parse anything at all. Version 0.22.0 worked fine
[JMdict.zip](https://github.com/tafia/quick-xml/files/11202365/JMdict.zip)
This is just a trimmed file of the JMdict file to demonstrate the issue. You can find the original file [here](http://ftp.edrdg.org/pub/Nihongo/JMdict.gz).

Working v0.22.0 Code:
```rust
use quick_xml::{events::Event, Reader};
use std::{fs::File, io::BufReader};

fn main() {
    let mut reader = Reader::from_reader(BufReader::new(File::open("./JMdict_short").unwrap()));
    reader.trim_text(true);
    let mut buf = vec![];

    loop {
        match reader.read_event(&mut buf) {
            Ok(Event::Start(ref e)) => {
                if let b"entry" = e.name() {
                    println!("{}", std::str::from_utf8(e.name()).unwrap());
                }
            }

            Ok(Event::Eof) => break,

            Err(e) => {
                panic!("{e:?}");
            }

            _ => (),
        }
    }
}
```

Broken v0.28.1 Code (same code, just migrated):
```rust
use quick_xml::{events::Event, Reader};
use std::{fs::File, io::BufReader};

fn main() {
    let mut reader = Reader::from_reader(BufReader::new(File::open("./JMdict_short").unwrap()));
    reader.trim_text(true);
    let mut buf = vec![];

    loop {
        match reader.read_event_into(&mut buf) {
            Ok(Event::Start(ref e)) => {
                if let b"entry" = e.name().0 {
                    println!("{}", std::str::from_utf8(e.name().0).unwrap());
                }
            }

            Ok(Event::Eof) => break,

            Err(e) => {
                panic!("{e:?}");
            }

            _ => (),
        }
    }
}
```

**Comment by Mingun** [comment] 2023-04-11 18:53
It seems that this bug is happened when `<!DOCTYPE >` content is too long to fit into `BufReader` buffer.

**Comment by JojiiOfficial** [comment] 2023-04-13 10:23
Interesting though that this is dependent on the buffer which should be transparent to the xml reader. But indeed increasing the buffer size fixes the issue.

**Comment by Mingun** [comment] 2024-09-19 17:57
Duplicate of #533

**Closed by Mingun** 2024-09-19 17:57 UTC
Labels: bug, help wanted
