### ISSUE TITLE
Serde can't deserialize cdata using $value

### ISSUE THREAD

**Issue by sify21** [tafia/quick-xml#186] opened 2020-01-09 12:34 UTC
rust definition:
```rust
#[derive(Debug, Deserialize, PartialEq)]
struct After {
    #[serde(rename = "$value")]
    body: Option<String>,
}
```
xml fragment:
```xml
<After><![CDATA[some string]]></After>
```
body field is set to None

**Comment by tafia** [comment] 2020-02-01 13:56
Indeed, CData nodes are currently ignored (as well as `Comments`, `PI`, `Decl`, `DocType`).
We could perhaps revisit this.

**Comment by filip-minic** [comment] 2020-04-01 07:26
Hi,

is there a way to fix this (workaround)? Also, it seems this is not serde related, in general quick-xml ignores CDATA, correct me if I am wrong?

For my use case this is also somewhat of a pain, since I have to first clean the xml, which is 20+ GB.

Best Regards

**Comment by sify21** [comment] 2020-04-01 08:04
while, I parsed my xml by hand, using the read_event method

**Comment by Mingun** [comment] 2022-05-21 21:50
Duplicate of #384

This bug is fixed.

**Closed by Mingun** 2022-05-21 21:50 UTC
