### ISSUE TITLE
xml nodes with namespaces cannot be serialized correctly

### ISSUE THREAD

**Issue by bahetiai** [tafia/quick-xml#409] opened 2022-06-30 05:56 UTC
code:
```rust
use quick_xml::de::{XmlRead};
use quick_xml::se::to_string;

use serde::Deserialize;
use serde::Serialize;

fn main() {
    let s = r#"<root><vt:first name="test"><second>value1</second><second>value2</second></vt:first></root>"#;
    let root:Root = quick_xml::de::from_str(s).unwrap();
    let result = to_string(&root).unwrap();
    println!("result = {}",result);
}

#[derive(Deserialize,Serialize,Debug)]
struct Root {
    #[serde(rename = "vt:first")]
    first: First,

}
#[derive(Deserialize,Serialize,Debug)]
pub struct First{
    name: String,

    #[serde(rename = "second")]
    other_field: Vec<Second>,
}
#[derive(Deserialize,Serialize,Debug)]
pub struct Second{
    #[serde(rename="$value")]
    body: String
}
```

but i got error "thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("missing field `vt:first`")', src/main.rs:10:48". Is there any other way to solve this problem?

**Comment by Mingun** [comment] 2022-06-30 07:58
Duplicate of #347

**Closed by Mingun** 2022-06-30 07:58 UTC
Labels: bug, serde, namespaces
