### ISSUE TITLE
Added quick-xml to Cargo.toml -> compilation error

### ISSUE THREAD

**Issue by culebron** [tafia/quick-xml#480] opened 2022-09-17 18:56 UTC
Cargo version: 1.59.0 
rustc version: 1.59.0
OS: Ubuntu 22.04

Made a blank new project:

    $ cargo new qxml

and edited `Cargo.toml`:
```[package]
name = "qxml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.25"
```

Compilation fails on both v0.25 and v0.24.1, and both in edition 2021 and 2018:
```
$ cargo build
...
...
...
   Compiling quick-xml v0.25.0
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
  --> /home/culebron/.cargo/registry/src/github.com-__________/quick-xml-0.25.0/src/writer.rs:62:6
   |
62 | impl<W: Write> Writer<W> {
   |      ^
63 |     /// Creates a `Writer` from a generic writer.
64 |     pub const fn new(inner: W) -> Writer<W> {
   |     --------------------------------------- function declared as const here
   |
   = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `quick-xml` due to previous error

```

When I change version to 0.23, it compiles.

Reading  the [issue](https://github.com/rust-lang/rust/issues/57563) dosen't give any idea what to do. Quick-xml documentation doesn't mention anything on this topic either.

**Comment by Mingun** [comment] 2022-09-17 19:31
Duplicate of #479

**Closed by Mingun** 2022-09-17 19:31 UTC
