### ISSUE TITLE
Remove extra newline when pretty printing text serialized from foreing types

### ISSUE THREAD

**Issue by RedIODev** [tafia/quick-xml#813] opened 2024-09-30 15:58 UTC
I currently have the problem that serializing types that serialize to text are not placed inline but on their own line.
Example:
```rust
use uuid::Uuid;
#[derive(From, Debug, Serialize, Deserialize)]
pub struct Guid {
    #[serde(rename = "@type")]
    pub id_type: String,
    #[serde(with = "simple_uuid")]
    #[serde(rename = "$text")]
    pub id: Uuid,
}
```
is serialized to (when the guid field is named "book:id"):
```xml
<book:id type="guid">
  3e114c9829ce41728902866e39b4e5c7
</book:id>
```
The required formatting for the target application is:
```xml
<book:id type="guid">3e114c9829ce41728902866e39b4e5c7</book:id>
```
I haven't found a way to change this behavior.
Great regards
RedIODev

**Comment by Mingun** [comment] 2024-09-30 17:10
Duplicate of #729

**Closed by Mingun** 2024-09-30 17:10 UTC
Labels: bug, duplicate, serde
