### ISSUE TITLE
Issue with serialization when using serde(flatten) 

### ISSUE THREAD

**Issue by Dekker1** [tafia/quick-xml#761] opened 2024-06-17 05:28 UTC
I ran into an issue where trying to use serde to serialize using quick-xml, does not work when you use `#[serde(flatten)]` in the root structure. However, the code seems to work when the struct is used further down in a nested structure, and moving the members of the struct into the original it works as well.

The following test case currently fails:
```rust
	#[test]
	fn flatten_serialize() {
		#[derive(Debug, PartialEq, Serialize)]
		struct A {
			a: i32,
			#[serde(flatten)]
			b: B,
		}
		#[derive(Debug, PartialEq, Serialize)]
		struct B {
			#[serde(rename = "@b")]
			b: i32,
		}

		let a = A {
			a: 1,
			b: B { b: 2 },
		};
		let output = quick_xml::se::to_string(&a).unwrap();
		assert_eq!(output, r#"<A a="1" b="2"/>"#);
	}
```

**Comment by Mingun** [comment] 2024-06-17 08:15
This is a fundamental flaw of serde flatten design and can be fixed only in serde. Duplicate of #714

**Closed by Mingun** 2024-06-17 08:15 UTC
Labels: bug, duplicate, wontfix, serde

**Comment by Dekker1** [comment] 2024-06-17 08:22
Thank you for the information, and the quick response. Fingers crossed the serde issue will get resolved at some point.

**Comment by Mingun** [comment] 2024-06-17 08:36
Actually, that is slight different problem, but also due to the flatten design and unavoidable without changes in serde. In you case error is `Unsupported("cannot serialize map without defined root tag")`. That message say that you try to serialize map which does not have a type name, so you must provide the one. [Map](https://docs.rs/serde/latest/serde/trait.Serializer.html#tymethod.serialize_map) serialization instead of [struct](https://docs.rs/serde/latest/serde/trait.Serializer.html#tymethod.serialize_struct) serialization is used because your struct contains flatten fields and therefore the overall set of fields for serialization is unknow at syntax level (at which proc macro works).

With two changes in you struct the serialization is work as expected, but deserialization will not work due to mentioned design flaw:
```rust

#[test]
fn issue761() {
    #[derive(Debug, PartialEq, Serialize)]
    struct A {
        #[serde(rename = "@a")]// <<<< Add (you want attribute)
        a: i32,
        #[serde(flatten)]
        b: B,
    }
    #[derive(Debug, PartialEq, Serialize)]
    struct B {
        #[serde(rename = "@b")]
        b: i32,
    }

    let a = A {
        a: 1,
        b: B { b: 2 },
    };
    let output = quick_xml::se::to_string_with_root("A", &a).unwrap();// <<<< Change
    assert_eq!(output, r#"<A a="1" b="2"/>"#);
}
```
