### ISSUE TITLE
Specify enum variant on colo with serde

### ISSUE THREAD

**Issue by carrascomj** [tafia/quick-xml#338] opened 2021-11-05 09:35 UTC
Related to #320

### Problem

Sometimes variants of an object in the XML file are specified with a colon.

```xml
<rdf:RDF>
    <bqbiol:is>
        <rdf:bag>
            <rdf:li rdf:resource="someuri.com">
            <rdf:li rdf:resource="someuri.com">
            <rdf:li rdf:resource="someuri.com">
        </rdf:bag>
    </bqbiol:is>
</rdf:RDF>
```

Here, `bqbiol` could be followed by `:encodes`, `:isPartOf` and more variants.

### Temporary solution

Hardcoded renames for each variant (check https://github.com/carrascomj/rust_sbml/blob/trunk/src/rdf.rs#L146 for the whole case):

```rust
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize)]
pub enum Bqbiol {
    #[serde(rename = "bqbiol:encodes")]
    Encodes {
        #[serde(rename = "$unflatten=rdf:Bag", default)]
        rdf_bag: RdfBag,
    },
    #[serde(rename = "bqbiol:hasPart")]
    HasPart {
        #[serde(rename = "$unflatten=rdf:Bag", default)]
        rdf_bag: RdfBag,
    },
    #[serde(rename = "bqbiol:encodes")]
    HasProperty {
        #[serde(rename = "$unflatten=rdf:Bag", default)]
        rdf_bag: RdfBag,
    }
}

// rest of stuff
#[derive(Deserialize, Serialize)]
pub struct Rdf {
    #[serde(rename = "$value")]
    pub inner: Vec<Bqbiol>,
}

#[derive(Deserialize, Serialize, Default)]
pub struct RdfBag {
    #[serde(rename = "$unflatten=rdf:li", default)]
    pub rdf_lis: Vec<RdfLi>,
}


#[derive(Deserialize, Serialize, Default)]
pub struct RdfLi {
    #[serde(rename = "rdf:resource")]
    pub resource: String,
}
```

### Proposed API

I would like a way to specify that the variants by name:

```rust
#[derive(Deserialize, Serialize)]
pub enum BqbiolVerb {
    Encodes,
    HasPart,
    HasProperty,
}


#[derive(Deserialize, Serialize)]
pub struct Bqbiol {
    // some renames ocurring here
    verb: BqbiolVerb,
    // some renames ocurring here
    bag: RdfBag,
}

// rest of stuff
#[derive(Deserialize, Serialize)]
pub struct Rdf {
    #[serde(rename = "$value")]
    pub inner: Vec<Bqbiol>,
}
```

 Or at least a better way. I guess it is a bit too specific and maybe it would require implementing my own `Serialize/Deserialize` impls, but I found a bit confusing how to do that in the context of quick-xml.

**Comment by Mingun** [comment] 2022-05-25 15:59
The names with colons are namespaced names, so this is essentially a duplicate of #218.

**Closed by Mingun** 2022-05-25 15:59 UTC
Labels: enhancement, serde, namespaces
