### ISSUE TITLE
Deserialization of a doctype with very long content fails

### ISSUE THREAD

**Issue by benoitryder** [tafia/quick-xml#533] opened 2022-12-28 20:46 UTC
`quick_xml::de::from_reader()` parsing fails if the XML contains a doctype with content larger than the internal `BufRead` capacity.
For instance
```xml
<!DOCTYPE [
<!-- A very very long comment *snipped* -->
]>
<X></X>
```

Here is a minimal code to reproduce this issue. It fails with an `ExpectedStart` error.
```rust
use std::io::Write;
use serde::Deserialize;

#[derive(Deserialize)]
struct X {}

fn main() {
    {
        let mut file = std::fs::File::create("test.xml").unwrap();
        let header = &"<!DOCTYPE X [<!--";
        let footer = &"-->]><X></X>";
        let padding = 8192 - (header.len() + 2);
        write!(file, "{header}{:1$}{footer}", "", padding).unwrap();
    }

    let file = std::fs::File::open("test.xml").unwrap();
    let reader = std::io::BufReader::new(file);
    let _: X = quick_xml::de::from_reader(reader).unwrap();
}
```
`Cargo.toml` content
```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.27.1", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
```

* When decreasing the padding size, or using `BufReader::with_capacity()` to increase the buffer, even of 1 byte, there is no error.
* Other `BufRead` implementations don't have this issue (checked with `&[u8]` and `stdin`).
* Content does not have to be in one "block". The same issue occurs for a doctype split into multiple declarations and comments.
* With a longer doctype with real content, the error may be different. For instance it may complains about an invalid `!` from a `!ENTITY` tag.
* No issue with `serde-xml-rs`, even for larger comments.
* Tested on Windows, with rustc 1.66.0.

**Comment by Mingun** [comment] 2023-05-19 17:39
Feel free to submit a PR. Actually, the #590 seems a duplicate of this bug, so you can start from my findings there.

**Comment by hecatia-elegua** [comment] 2023-05-19 19:33
Looks a lot like a trimming problem.
`StartTrimmer.trim_start` doesn't get updated like it says "This field is set to true after reading each event except Event::Text and Event::CData".

**Comment by Mingun** [comment] 2023-05-19 20:50
Unlikely. `StartTrimmer.trim_start` updated here:
https://github.com/tafia/quick-xml/blob/84b07b4e5c9a201b3d3d7fa95c1e8c33ecbe6dd2/src/de/mod.rs#L2900

All whitespaces need to persist until we will sure that we can trim them. Motivation in #520

**Comment by hecatia-elegua** [comment] 2023-05-19 20:58
It isn't _only_ "each event except Event::Text and Event::CData" but also in this catch-all:
https://github.com/tafia/quick-xml/blob/84b07b4e5c9a201b3d3d7fa95c1e8c33ecbe6dd2/src/de/mod.rs#L2898
Maybe docs just need an update here.

What I want might just be #561. hmm

**Comment by hecatia-elegua** [comment] 2023-05-24 19:54
My problem might be off-topic, but #603 got the same idea.

**Comment by BlueGreenMagick** [comment] 2024-09-19 17:18
An even more minimal code to reproduce the error:

```rust
use serde::Deserialize;
use std::io::BufReader;

#[derive(Deserialize)]
struct X {}

fn main() {
    let xml = "<!DOCTYPE X [<!-- -->]><X></X>";
    let reader = BufReader::with_capacity(20, xml.as_bytes());
    let _: X = quick_xml::de::from_reader(reader).unwrap();
}
```

**Closed** 2024-09-20 16:42 UTC
Labels: bug, help wanted
