### ISSUE TITLE
Errors should contain buffer positions

### ISSUE THREAD

**Issue by phillord** [tafia/quick-xml#411] opened 2022-07-08 12:26 UTC
Currently, quick-xml errors do not carry the buffer position. That works okay when parsing XML directly, but it harder when using using quick-xml inside another library, since any errors raised by quick-xml must be handled explicitly by code which has access to the reader rather than using `?` and a  `From` conversion.

If #109 were addressed, it would be nicer still to get a line/column locator!

**Comment by Mingun** [comment] 2022-07-08 14:28
I close this as duplicate of #313, because the solution would be the same

**Closed** 2022-07-08 14:28 UTC
