### ISSUE TITLE
Handling varying structure

### ISSUE THREAD

**Issue by SorenHolstHansen** [tafia/quick-xml#323] opened 2021-09-30 12:58 UTC
I am fetching a bunch of xml-text from an api which I want to read and deserialize. Most of the structure is quite uniform, but one part is not. That part can look like one of the three following

```xml
<member>
  <memberData>
      <p>Some text here inside a p-tag</p>
  </memberData>
</member>
```
```xml
<member>
  <memberData>
      Some text here not inside a p-tag
  </memberData>
</member>
```
or
```xml
<member>
  <memberData>
      <p>Some text here with redundant stuff after</p>
      <div>
        <img />
      </div>
  </memberData>
<member>
```
I have tried to model it like this because I am only interested in the text.
```rust
#[derive(Debug, Deserialize, PartialEq)]
struct MemberData {
    #[serde(rename = "$value")]
    body: String,
}
```
Now this works for the first two cases, but for the last one i get
```rust
Error: Custom("duplicate field `$value`")
```
Is there some way of handling this?

**Comment by Mingun** [comment] 2022-05-21 20:42
Duplicate of #257

**Closed by Mingun** 2022-05-21 20:42 UTC
