### ISSUE TITLE
CDATA  Serializer

### ISSUE THREAD

**Issue by kulame** [tafia/quick-xml#485] opened 2022-09-28 08:42 UTC
my target xml string is  
```xml
<xml>
  <ToUserName><![CDATA[toUser]]></ToUserName>
  <FromUserName><![CDATA[fromUser]]></FromUserName>
</xml>
```
my serde struct is 
```rust
#[derive(Serialize, Deserialize, Debug)]
pub struct ImageReplyMessage {
    #[serde(rename = "$unflatten=ToUserName")]
    pub to_user_name: String,
    #[serde(rename = "$unflatten=FromUserName")]
    pub from_user_name: String,
}
```
how can i Serialize the to_user_name  to CDATA value?

**Comment by Mingun** [comment] 2022-09-28 09:34
Duplicate of #353

**Closed by Mingun** 2022-09-28 09:34 UTC

**Comment by kulame** [comment] 2022-09-28 09:51
any solution fot it?

**Comment by kulame** [comment] 2022-09-28 09:51
any solution fot it?
