### ISSUE TITLE
Question: How to deserialize arbitrary tag

### ISSUE THREAD

**Issue by thorstenhater** [tafia/quick-xml#320] opened 2021-09-12 08:31 UTC
I have a question and I hope this is right channel to ask. I am trying to deserialize a data format based
on XML using serde, which essentially boils down to
```xml
<root>
  <kind name="A" />
  <item kind="A">
    ...
  </item>
  <kind name="B" />
  <B>
    ...
  </B>
</root>
```
Note how the `B` tag can be used a shorthand for `item kind="B"`.
I have a working implemention for the non-shorthand part that looks like this
```rs
// These have more inner structure, omitted for brevity
#[deriving(Deserialize)]
struct Kind { ... }
#[deriving(Deserialize)]
struct Item { ... }

#[deriving(Deserialize)]
enum RootBody {
   Item(Item),
   Kind(Kind),
}

#[deriving(Deserialize)]
struct Root {
  #[serde(rename="$value")]
  body: Vec<RootBody>,
}
```
However, how to capture the short-hand feature? Using the pattern from the
JSON examples 
```rs
#[deriving(Deserialize)]
struct Root {
  #[serde(rename="$value")]
  body: Vec<RootBody>,
  #[serde(flatten)]
  unknown: Map<String, Value>
}
```
fails with `Custom("missing field $value")'`. I have also tried `deserialize-enum-str` and 
had no success.

**Comment by Mingun** [comment] 2022-05-21 19:37
Duplicate of #326

**Closed by Mingun** 2022-05-21 19:37 UTC
Labels: serde
